language: node_js
node_js:
- 6
- 8
- 10
- 12
- 14

before_install:
  - npm i -g npm@latest

notifications:
  slack:
    secure: WIYC8teZRQOYEpKs/5bQmf5i1o9dTcBoIK5WfYjZIxueV/Ohx9hQwzV/NHkJkLUE9EKQ6w5ieLLQEQxWEonKMk02SBDIR0dC0a+Ewh3K+zCfnu0XRITXJlLsrHoZIMQaqBqbR83C/kxPwkXBuHWFyevZXwFGeZdy6uqt/97t0UgXUKvaIL2vI7Kg4TWobRNZiqVNHc3+TzfB9UzDxByYF/bbJw18D8pqeHZjcfhL6muJLRzGoXvlF6Kw2jmv/z2AxMnLgOqWbKCyOcT2zdNRs6RdzAZxncGvxTKuyqiSoLgPPKVlOmWJfyQoz17ZkVEjfVTV9IOfBaIEbM/OvEoDWvRAp5TrQnCOX3BbUbUrZhoYmarDMqTP91r50Ww2k1NyVMMViWAxt1VSzofe+WD/99Oyk7Q+WsVqWob51938+V+xVF2ZwL1shcDQxdCSbM0eHcyUg5baLbevhTbxolilzTvQNk+7+RLPTJmYUvacmMovZWaTFUGkgwtTTnIke82Amh6NIhw2N8o4l9yAZJPWpYmYj69cxF7802YV2Dc6B5ODzN9PS10oCJBS/dRJezxYHae1JnRf8IcVFOCYm6QxzuLdrLnsIjmKcA5gXAtT2HF/uF0lkrensZEekUvROTrn3UM3iq0QMYx4WlZVIH0+FGcmHDCoawJuAMWUtSGjXGQ=
