language: node_js
node_js:
  - "6"
  - "8"
  - "10"

after_success:
  - ./node_modules/.bin/codecov -f coverage/*.json # upload code coverage report

notifications:
  slack:
    secure: "CjUYe0JN7l9IKGbhjKYrQddvr1yhtu/74aKk7eaA3iKjhCfOq8MghjOGHF0tjluJA6qSiAvKKSS9hqqVYdQd8tMISdv2X7hsfLYJHwSuyPYIDk8TsthHlOa9pyEemv94iXfV5qkTD1y0MX53QioZxLjQvRcJZGLpk3e5pak71AXf5y3y1VWe8vjhBcCAD3HyMedgEiM/S/mfC3zKct+Hky9Du5KWwY21KaFBYsX8JaHotVsElSDikSOLIe/Px615Jlwc1f0scoWvyM0mRihYW99W02p9O58VatOAZy/RlG7Ney2mbs/sYI1a2Sjbh+dLw1tdI0MroJgdP8X4nDcfBDhmneu0/iXyy3CYw8aKwpqvNowQsGZVzd3MsLvn8zFLE/A4ulEd1MuThW921BpODmL9mzU2qSqVkUk/WIoJcdudD4mOvogn9fEax3STw/wmxKgbrHkSALN8jM2NoaeoIFuwJnbmrqHj8r+b5p0vxHIxYXhmi15Ehu5rRYdJD2IlvXoFvhV+Pzzm7Wq84jdVTWnhO9N1Uoqrln8OzX5YKA67bI/aL6OSi2ryPIZ3tyvn+p2OIyoFvLhiyMI89V4fd1ZD7zu7N5/e7nyYnNMFDxcWy+fI7zAsfXcKxYf1S7jviitQeNkT8M+eDu8z8ZUVfIFAipZtsLg++GthI1BZdaM="
