language: node_js
node_js:
- 6
- 8
- 10

notifications:
  slack:
    secure: GF7liegFvjsl2pGkEQB8T67J/tzgnFrXkdpoOiCwSVdgL2vPHXJmlvg76lep+Yc09jANT1vBsRj/4fjsPBc41MhqHa3vU9vJsyKSgDt16OHNjosQ4LZLuCzYEU6J/+pFEkqoV3pOis6lcjO6OePy7SnuEP7Urx1angOcTD8fipTdv9R/aHVphe8w8bTVP1fPV63V7wlVrO//3IxGLADVy2DeCkZUVSCPNkXWm4MByW4dU4R7arsN5y9/nspxmErILRRJBFg8VZzEqB5hWHJJf0V/8SlieChTUVujloOTu8lMlJfCirh58Fe+Mlhy3vG2WdAaqG3LE2MJ6q1KiULAR5JzqgvtgjlYcKMkqLYT5I/oW6WwtrVsLcES5xJ4S+UsA/DlTcq31KrREhJqQZ3vsBvBbzlJfxPqhaSMBy1VnrWsdoYngd84IeX4ecW7sFXzdaXW6mMf+tlg77LDK1s9oGOtsbVkiIVVESW2Nwm8r2VSY+ppvwdCL3OzK1R4iRLCJ+R/EQraVD7SJhsWBvwp/kBUihlaQqyDRdDhgf5bJr9e4seEm7sP7UeorOTC7UixE4pfriR3vNBIocR+sIc+UxlRrjcR5zI/KDnmkDBTZTFpHC4NZJRuGDcwnbndfckqzwmrAXZ5ZAEbzAvge1Vl+sYGETzN6Da4J79Js0X1+D0=
