language: node_js
node_js:
- 6
- 8
- 10

notifications:
  slack:
    secure: lKy7kCNJyeYPkU7Z4Jv94MkHQiegNmDw0HP9gBS0fW4yJQQCe7b7MRLgwSQlc9T4g5U7OmaUUnvnP06Fd2xP35gqGaBH2/r0rgtF6mWOVsGtgWe7QvAFBQ7cSJbXF7hjIE+CBShpG2cRP6wXDfEweM/Hf87KnFPoHNzjv7jxtHfAszBJh1eMO+lnSmtjHnrTOnPKC7Wy3qXmnO7mR8RdVYwSa/Dz83R94AjxLsPYuZL0wWFd0r6s7euEGC7bCC4higyFUpdYQyFY5nb30ya8B7/BSUPMGltfNvE73DQg+W4udRLjXDlsty3NP6/bmgAornhH2nk93IJROWc4S2+DyLb26Y38YTq0b9xHJZhBlWOvUAXIb1sReoHQmDuXKam5AjjfSUssJPVtS6NJJQ82sYU9xT8eA529/sVlbp2Tf4NK+mTOigvk40UlWNH5IjEAQAvQf+p5eZ3b5CMVqsWebOgftdQrVh+sFKQRTS8+CA2aNGjxkZjpqo5Lhg34sYjDNAEtI7Jmq7ebjY6iKWfwzPAluDu4wNvZFmTznOnnRwFrrs5ToX+2JvRmZNo0xC080XcyN7+g0CEgU4UJmwXalZXp9Y7f0egWpd4ZcIXMsPY20u2LR/YuDflxFgzYJV6C+vHLXIvfNrJhgN51m5IuOESfU0Nzw/BZKAQuR0pio/A=
