language: node_js
node_js:
- 6
- 8
- 10

notifications:
  slack:
    secure: sR9vN6EvnGcrzfdr1klqe/QCnhE5TMrmFqrP39Ydubtkgi0A6kJiNOLAkgqzvUS6F5IhC/zG/X8YcgXulS40VAYqfHZn8T7W5n5wGNezdeCRyBLq3qud74xNHFplLnUzjiLuwu+oQHjeEc7ElQ6NwomyaL+qVoZOctkEqvviLIeRX7fmyLMTJH2TQYj2XlHkCAsQzgXUkrAIkE2P3numQ+CCMCsMjTilgrTATmH0gAExk0Pc+MLsgAT5jllF1je4vhOBUI9nreBSSuTrLzvn0rWc7klNtV5Bsy5xg2C8W1LlylfluanIRzs5DrXNbm2xzMIwKbySb2Hw0hoYcH51jmaBdHtRQMyX++6YIlEx/etCnTPia4j330KvwFTHOgshpkr/YeZy8NE4genEbfvJYo3EQUOIF88qBPPdCF4DVHCC/mMEInSk2qgvr/h9gviFdiSy92PSnc171fNoBWfWnwRCFRwUotXMT9PWWULDvD9fZ7ZvY75du66lK3gH4yhwEfo4iNn8WMp6QBQm1N+zTy6unlJ1Zxy9uCzSktuXaRJc2f5wZL9XkG1gC3RKZHtOSB7LjaTj+xam/GK1Fdwl29IjooPPr5nMt0YPoQZBig8AiKLHAJE/xjG5RoKqI+TEJdabwXWnQtFwMMyuGq8JN2m4J73znnKtOOWGEmPotqw=
