name: 'CI'

on:
  workflow_call:
    inputs:	
      config-path:	
        required: false	
        type: string
  pull_request:
    branches:
    - master

jobs:
  lint-test-typecheck:
    name: 'Lint and Test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Unit Test
        run: yarn test
      - name: Type Check
        run: yarn build
